FROM node:16.13.1-alpine3.13 AS builder

RUN apk update
RUN apk add git
# Set working directory
WORKDIR /app
RUN yarn global add turbo@1.3.4
COPY . .
RUN turbo prune --scope=aleo-tank --docker

# Add lockfile and package.json's of isolated subworkspace
FROM node:16.13.1-alpine3.13 AS installer
RUN apk update
WORKDIR /app
COPY --from=builder /app/.yarnrc.yml ./
COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock
COPY --from=builder /app/out/full/ .
COPY .gitignore .gitignore
COPY turbo.json turbo.json

RUN yarn install
RUN yarn turbo run build --filter=aleo-tank

FROM node:16.13.1-alpine3.13 AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 midway
RUN adduser --system --uid 1001 midway
USER midway
COPY --from=installer /app .

ENTRYPOINT ["npm", "run", "online"]
